#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("iBeaconsEverywhereAndroid.Resource", IsApplication=true)]

namespace iBeaconsEverywhereAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int beacon_blueberry = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int beacon_gray = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int beacon_icy = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_distance = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dot = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_launcher = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_square_far = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_square_immediate = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_square_near = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_square_unknown = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int accuracy = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int dot_far = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int dot_immediate = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int dot_near = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int dot_unknown = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int image = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int image_beacon = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout1 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout2 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int major = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int minor = 2131099656;
			
			// aapt resource value: 0x7f060010
			public const int no_beacons = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int progressBar = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int rssi = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int subtitle = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int title = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int uuid = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Details = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemBeacon = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyBaseTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
