#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("iBeaconsEverywhere.Wear.Resource", IsApplication=true)]

namespace iBeaconsEverywhere.Wear
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010008
			public const int cameraBearing = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int cameraTargetLat = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int cameraTargetLng = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int cameraTilt = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int cameraZoom = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int circleCrop = 2130771974;
			
			// aapt resource value: 0x7f01001c
			public const int circle_border_color = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public const int circle_border_width = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int circle_color = 2130771992;
			
			// aapt resource value: 0x7f01001d
			public const int circle_padding = 2130771997;
			
			// aapt resource value: 0x7f010019
			public const int circle_radius = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int circle_radius_pressed = 2130771994;
			
			// aapt resource value: 0x7f01002f
			public const int circular_layout_gravity = 2130772015;
			
			// aapt resource value: 0x7f010030
			public const int circular_text_size = 2130772016;
			
			// aapt resource value: 0x7f010023
			public const int dotColor = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int dotColorSelected = 2130772004;
			
			// aapt resource value: 0x7f010028
			public const int dotFadeInDuration = 2130772008;
			
			// aapt resource value: 0x7f010026
			public const int dotFadeOutDelay = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int dotFadeOutDuration = 2130772007;
			
			// aapt resource value: 0x7f010025
			public const int dotFadeWhenIdle = 2130772005;
			
			// aapt resource value: 0x7f010021
			public const int dotRadius = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int dotRadiusSelected = 2130772002;
			
			// aapt resource value: 0x7f010029
			public const int dotShadowColor = 2130772009;
			
			// aapt resource value: 0x7f01002b
			public const int dotShadowDx = 2130772011;
			
			// aapt resource value: 0x7f01002c
			public const int dotShadowDy = 2130772012;
			
			// aapt resource value: 0x7f01002a
			public const int dotShadowRadius = 2130772010;
			
			// aapt resource value: 0x7f010020
			public const int dotSpacing = 2130772000;
			
			// aapt resource value: 0x7f010005
			public const int imageAspectRatio = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int imageAspectRatioAdjust = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010017
			public const int layout_box = 2130771991;
			
			// aapt resource value: 0x7f01000d
			public const int liteMode = 2130771981;
			
			// aapt resource value: 0x7f010007
			public const int mapType = 2130771975;
			
			// aapt resource value: 0x7f01002d
			public const int rectLayout = 2130772013;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f01002e
			public const int roundLayout = 2130772014;
			
			// aapt resource value: 0x7f01001e
			public const int shadow_width = 2130771998;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			// aapt resource value: 0x7f01000e
			public const int uiCompass = 2130771982;
			
			// aapt resource value: 0x7f010016
			public const int uiMapToolbar = 2130771990;
			
			// aapt resource value: 0x7f01000f
			public const int uiRotateGestures = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int uiScrollGestures = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int uiTiltGestures = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int uiZoomControls = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int uiZoomGestures = 2130771987;
			
			// aapt resource value: 0x7f01001f
			public const int update_interval = 2130771999;
			
			// aapt resource value: 0x7f010014
			public const int useViewLifecycle = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int zOrderOnTop = 2130771989;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f07000a
			public const int black = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int blue = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int card_default_background = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int common_action_bar_splitter = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int common_signin_btn_dark_text_default = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int common_signin_btn_dark_text_disabled = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_signin_btn_dark_text_focused = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_signin_btn_dark_text_pressed = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int common_signin_btn_default_background = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int common_signin_btn_light_text_default = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int common_signin_btn_light_text_disabled = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int common_signin_btn_light_text_focused = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int common_signin_btn_light_text_pressed = 2131165189;
			
			// aapt resource value: 0x7f07001d
			public const int common_signin_btn_text_dark = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int common_signin_btn_text_light = 2131165214;
			
			// aapt resource value: 0x7f07000d
			public const int dark_blue = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int dark_grey = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int disabled_text_light = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int dismiss_close = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int dismiss_close_pressed = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int dismiss_overlay_bg = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int green = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int grey = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int light_grey = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int orange = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int primary_text_dark = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int primary_text_light = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int red = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int secondary_text_light = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int semitransparent_grey = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int white = 2131165212;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int card_content_padding_rect_top = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int close_button_diameter = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int dismiss_padding = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int card_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int card_frame = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int card_frame_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int close_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_full_open_on_phone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_ic_googleplayservices = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_disabled_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_disabled_focus_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_disabled_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_focus_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_focus_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_normal_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_normal_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_pressed_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_pressed_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_disabled_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_disabled_focus_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_disabled_focus_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_disabled_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_focus_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_focus_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_normal_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_normal_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_pressed_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_pressed_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int confirmation_animation = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int generic_confirmation_00163 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int generic_confirmation_00164 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int generic_confirmation_00165 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int generic_confirmation_00166 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int generic_confirmation_00167 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int generic_confirmation_00168 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int generic_confirmation_00169 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int generic_confirmation_00170 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int generic_confirmation_00171 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int generic_confirmation_00172 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int generic_confirmation_00173 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int generic_confirmation_00174 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int generic_confirmation_00175 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int generic_confirmation_00185 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int generic_confirmation_00186 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int generic_confirmation_00187 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int generic_confirmation_00188 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int generic_confirmation_00189 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int generic_confirmation_00190 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int generic_confirmation_00191 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int generic_confirmation_00192 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int generic_confirmation_00193 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int go_to_phone_00156 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int go_to_phone_00157 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int go_to_phone_00158 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int go_to_phone_00159 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int go_to_phone_00160 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int go_to_phone_00161 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int go_to_phone_00162 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int go_to_phone_00163 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int go_to_phone_00164 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int go_to_phone_00165 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int go_to_phone_00166 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int go_to_phone_00167 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int go_to_phone_00168 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int go_to_phone_00169 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int go_to_phone_00170 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int go_to_phone_00171 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int go_to_phone_00172 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int go_to_phone_00173 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int go_to_phone_00174 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int go_to_phone_00175 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int go_to_phone_00176 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int go_to_phone_00177 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int go_to_phone_00178 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int go_to_phone_00185 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int go_to_phone_00186 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int go_to_phone_00187 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int go_to_phone_00188 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int go_to_phone_00189 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int go_to_phone_00190 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int go_to_phone_00191 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int go_to_phone_00192 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int go_to_phone_00193 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int go_to_phone_00194 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int go_to_phone_00195 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int go_to_phone_00196 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int go_to_phone_00197 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int go_to_phone_00198 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int go_to_phone_00199 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int go_to_phone_00200 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int go_to_phone_00210 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int go_to_phone_00211 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int go_to_phone_00212 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int go_to_phone_00213 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int go_to_phone_00214 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int go_to_phone_00215 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int go_to_phone_00216 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int go_to_phone_00217 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int go_to_phone_00218 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int go_to_phone_00219 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int go_to_phone_00220 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int go_to_phone_00221 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int go_to_phone_00222 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int go_to_phone_00223 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int go_to_phone_00224 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int go_to_phone_animation = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int ic_full_cancel = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int ic_full_sad = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int ic_plusone_medium_off_client = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int ic_plusone_small_off_client = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int ic_plusone_standard_off_client = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int ic_plusone_tall_off_client = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int Icon = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int powered_by_google_dark = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int powered_by_google_light = 2130837620;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int action_error = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int action_success = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int adjust_height = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int adjust_width = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int all = 2131099656;
			
			// aapt resource value: 0x7f060013
			public const int animation = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int bottom = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int center = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int center_horizontal = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int center_vertical = 2131099663;
			
			// aapt resource value: 0x7f060016
			public const int dismiss_overlay_button = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int dismiss_overlay_explain = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int error_message = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int hybrid = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int left = 2131099658;
			
			// aapt resource value: 0x7f060018
			public const int main = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int message = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int none = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int normal = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int right = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int satellite = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int terrain = 2131099655;
			
			// aapt resource value: 0x7f060019
			public const int text = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int title = 2131099674;
			
			// aapt resource value: 0x7f06000c
			public const int top = 2131099660;
			
			// aapt resource value: 0x7f060017
			public const int watch_view_stub = 2131099671;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int google_play_services_version = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int confirmation_activity_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dismiss_overlay = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RectangleMain = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RoundMain = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int watch_card_content = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int gtm_analytics = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f08001e
			public const int app_name = 2131230750;
			
			// aapt resource value: 0x7f080003
			public const int common_android_wear_notification_needs_update_text = 2131230723;
			
			// aapt resource value: 0x7f080010
			public const int common_android_wear_update_text = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int common_android_wear_update_title = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int common_google_play_services_enable_button = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int common_google_play_services_enable_text = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int common_google_play_services_enable_title = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int common_google_play_services_error_notification_requested_by_msg = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int common_google_play_services_install_button = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int common_google_play_services_install_text_phone = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int common_google_play_services_install_text_tablet = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int common_google_play_services_install_title = 2131230726;
			
			// aapt resource value: 0x7f080014
			public const int common_google_play_services_invalid_account_text = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int common_google_play_services_invalid_account_title = 2131230739;
			
			// aapt resource value: 0x7f080004
			public const int common_google_play_services_needs_enabling_title = 2131230724;
			
			// aapt resource value: 0x7f080012
			public const int common_google_play_services_network_error_text = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int common_google_play_services_network_error_title = 2131230737;
			
			// aapt resource value: 0x7f080001
			public const int common_google_play_services_notification_needs_installation_title = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int common_google_play_services_notification_needs_update_title = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int common_google_play_services_notification_ticker = 2131230720;
			
			// aapt resource value: 0x7f080015
			public const int common_google_play_services_unknown_issue = 2131230741;
			
			// aapt resource value: 0x7f080017
			public const int common_google_play_services_unsupported_text = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int common_google_play_services_unsupported_title = 2131230742;
			
			// aapt resource value: 0x7f080018
			public const int common_google_play_services_update_button = 2131230744;
			
			// aapt resource value: 0x7f08000f
			public const int common_google_play_services_update_text = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int common_google_play_services_update_title = 2131230733;
			
			// aapt resource value: 0x7f08001b
			public const int common_open_on_phone = 2131230747;
			
			// aapt resource value: 0x7f080019
			public const int common_signin_button_text = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int common_signin_button_text_long = 2131230746;
			
			// aapt resource value: 0x7f08001c
			public const int hello_rect = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int hello_round = 2131230749;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int CardText = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int CardTitle = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int DismissOverlayText = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int DotsPageIndicatorStyle = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int TextAppearance_Wearable_Large = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int TextAppearance_Wearable_Medium = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int TextAppearance_Wearable_Small = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int TextView_Large = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int TextView_Large_Light = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int TextView_Medium = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int TextView_Medium_Light = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int TextView_Small = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int TextView_Small_Light = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int Theme_Wearable = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int Theme_Wearable_Modal = 2131361806;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] BoxInsetLayout_Layout = new int[]
			{
					2130771991};
			
			// aapt resource value: 0
			public const int BoxInsetLayout_Layout_layout_box = 0;
			
			public static int[] CircledImageView = new int[]
			{
					16843033,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 0
			public const int CircledImageView_android_src = 0;
			
			// aapt resource value: 5
			public const int CircledImageView_circle_border_color = 5;
			
			// aapt resource value: 4
			public const int CircledImageView_circle_border_width = 4;
			
			// aapt resource value: 1
			public const int CircledImageView_circle_color = 1;
			
			// aapt resource value: 6
			public const int CircledImageView_circle_padding = 6;
			
			// aapt resource value: 2
			public const int CircledImageView_circle_radius = 2;
			
			// aapt resource value: 3
			public const int CircledImageView_circle_radius_pressed = 3;
			
			// aapt resource value: 7
			public const int CircledImageView_shadow_width = 7;
			
			public static int[] DelayedConfirmationView = new int[]
			{
					2130771999};
			
			// aapt resource value: 0
			public const int DelayedConfirmationView_update_interval = 0;
			
			public static int[] DotsPageIndicator = new int[]
			{
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012};
			
			// aapt resource value: 3
			public const int DotsPageIndicator_dotColor = 3;
			
			// aapt resource value: 4
			public const int DotsPageIndicator_dotColorSelected = 4;
			
			// aapt resource value: 8
			public const int DotsPageIndicator_dotFadeInDuration = 8;
			
			// aapt resource value: 6
			public const int DotsPageIndicator_dotFadeOutDelay = 6;
			
			// aapt resource value: 7
			public const int DotsPageIndicator_dotFadeOutDuration = 7;
			
			// aapt resource value: 5
			public const int DotsPageIndicator_dotFadeWhenIdle = 5;
			
			// aapt resource value: 1
			public const int DotsPageIndicator_dotRadius = 1;
			
			// aapt resource value: 2
			public const int DotsPageIndicator_dotRadiusSelected = 2;
			
			// aapt resource value: 9
			public const int DotsPageIndicator_dotShadowColor = 9;
			
			// aapt resource value: 11
			public const int DotsPageIndicator_dotShadowDx = 11;
			
			// aapt resource value: 12
			public const int DotsPageIndicator_dotShadowDy = 12;
			
			// aapt resource value: 10
			public const int DotsPageIndicator_dotShadowRadius = 10;
			
			// aapt resource value: 0
			public const int DotsPageIndicator_dotSpacing = 0;
			
			public static int[] LoadingImageView = new int[]
			{
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[]
			{
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			public static int[] WatchViewStub = new int[]
			{
					2130772013,
					2130772014};
			
			// aapt resource value: 0
			public const int WatchViewStub_rectLayout = 0;
			
			// aapt resource value: 1
			public const int WatchViewStub_roundLayout = 1;
			
			public static int[] WearableHeaderTextView = new int[]
			{
					2130772015,
					2130772016};
			
			// aapt resource value: 0
			public const int WearableHeaderTextView_circular_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int WearableHeaderTextView_circular_text_size = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
